package ModSec.entidades;
// Generated 10-11-2014 10:38:28 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CtasUsuarios generated by hbm2java
 */
public class CtasUsuarios  implements java.io.Serializable {


     private int id;
     private CtasUsuarios ctasUsuarios;
     private String login;
     private String password;
     private char cambiarpass;
     private Date fechacaducta;
     private Date fechaultmod;
     private Date fechaulting;
     private Set logs = new HashSet(0);
     private Set ctasUsuarioses = new HashSet(0);

    public CtasUsuarios() {
    }

	
    public CtasUsuarios(int id, CtasUsuarios ctasUsuarios, String login, char cambiarpass, Date fechaultmod, Date fechaulting) {
        this.id = id;
        this.ctasUsuarios = ctasUsuarios;
        this.login = login;
        this.cambiarpass = cambiarpass;
        this.fechaultmod = fechaultmod;
        this.fechaulting = fechaulting;
    }
    public CtasUsuarios(int id, CtasUsuarios ctasUsuarios, String login, String password, char cambiarpass, Date fechacaducta, Date fechaultmod, Date fechaulting, Set logs, Set ctasUsuarioses) {
       this.id = id;
       this.ctasUsuarios = ctasUsuarios;
       this.login = login;
       this.password = password;
       this.cambiarpass = cambiarpass;
       this.fechacaducta = fechacaducta;
       this.fechaultmod = fechaultmod;
       this.fechaulting = fechaulting;
       this.logs = logs;
       this.ctasUsuarioses = ctasUsuarioses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public CtasUsuarios getCtasUsuarios() {
        return this.ctasUsuarios;
    }
    
    public void setCtasUsuarios(CtasUsuarios ctasUsuarios) {
        this.ctasUsuarios = ctasUsuarios;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public char getCambiarpass() {
        return this.cambiarpass;
    }
    
    public void setCambiarpass(char cambiarpass) {
        this.cambiarpass = cambiarpass;
    }
    public Date getFechacaducta() {
        return this.fechacaducta;
    }
    
    public void setFechacaducta(Date fechacaducta) {
        this.fechacaducta = fechacaducta;
    }
    public Date getFechaultmod() {
        return this.fechaultmod;
    }
    
    public void setFechaultmod(Date fechaultmod) {
        this.fechaultmod = fechaultmod;
    }
    public Date getFechaulting() {
        return this.fechaulting;
    }
    
    public void setFechaulting(Date fechaulting) {
        this.fechaulting = fechaulting;
    }
    public Set getLogs() {
        return this.logs;
    }
    
    public void setLogs(Set logs) {
        this.logs = logs;
    }
    public Set getCtasUsuarioses() {
        return this.ctasUsuarioses;
    }
    
    public void setCtasUsuarioses(Set ctasUsuarioses) {
        this.ctasUsuarioses = ctasUsuarioses;
    }




}


