package ModSec.entidades;
// Generated 10-11-2014 10:38:28 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Log generated by hbm2java
 */
public class Log  implements java.io.Serializable {


     private int id;
     private CtasUsuarios ctasUsuarios;
     private Date fechahora;
     private char tipooperacion;
     private String operacion;
     private String host;
     private String usrSo;

    public Log() {
    }

    public Log(int id, CtasUsuarios ctasUsuarios, Date fechahora, char tipooperacion, String operacion, String host, String usrSo) {
       this.id = id;
       this.ctasUsuarios = ctasUsuarios;
       this.fechahora = fechahora;
       this.tipooperacion = tipooperacion;
       this.operacion = operacion;
       this.host = host;
       this.usrSo = usrSo;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public CtasUsuarios getCtasUsuarios() {
        return this.ctasUsuarios;
    }
    
    public void setCtasUsuarios(CtasUsuarios ctasUsuarios) {
        this.ctasUsuarios = ctasUsuarios;
    }
    public Date getFechahora() {
        return this.fechahora;
    }
    
    public void setFechahora(Date fechahora) {
        this.fechahora = fechahora;
    }
    public char getTipooperacion() {
        return this.tipooperacion;
    }
    
    public void setTipooperacion(char tipooperacion) {
        this.tipooperacion = tipooperacion;
    }
    public String getOperacion() {
        return this.operacion;
    }
    
    public void setOperacion(String operacion) {
        this.operacion = operacion;
    }
    public String getHost() {
        return this.host;
    }
    
    public void setHost(String host) {
        this.host = host;
    }
    public String getUsrSo() {
        return this.usrSo;
    }
    
    public void setUsrSo(String usrSo) {
        this.usrSo = usrSo;
    }




}


