package ModSec.entidades;
// Generated 10-11-2014 10:38:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Modulos generated by hbm2java
 */
public class Modulos  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String descripcion;
     private int depjerq;
     private Set opcModulos = new HashSet(0);

    public Modulos() {
    }

	
    public Modulos(int id, String nombre, String descripcion, int depjerq) {
        this.id = id;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.depjerq = depjerq;
    }
    public Modulos(int id, String nombre, String descripcion, int depjerq, Set opcModulos) {
       this.id = id;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.depjerq = depjerq;
       this.opcModulos = opcModulos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public int getDepjerq() {
        return this.depjerq;
    }
    
    public void setDepjerq(int depjerq) {
        this.depjerq = depjerq;
    }
    public Set getOpcModulos() {
        return this.opcModulos;
    }
    
    public void setOpcModulos(Set opcModulos) {
        this.opcModulos = opcModulos;
    }




}


