package ModSec.entidades;
// Generated 10-11-2014 10:38:28 PM by Hibernate Tools 4.3.1



/**
 * OpcRol generated by hbm2java
 */
public class OpcRol  implements java.io.Serializable {


     private int id;
     private OpcModulo opcModulo;
     private Roles roles;
     private String autIns;
     private String autUpd;
     private String autDel;

    public OpcRol() {
    }

    public OpcRol(int id, OpcModulo opcModulo, Roles roles, String autIns, String autUpd, String autDel) {
       this.id = id;
       this.opcModulo = opcModulo;
       this.roles = roles;
       this.autIns = autIns;
       this.autUpd = autUpd;
       this.autDel = autDel;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public OpcModulo getOpcModulo() {
        return this.opcModulo;
    }
    
    public void setOpcModulo(OpcModulo opcModulo) {
        this.opcModulo = opcModulo;
    }
    public Roles getRoles() {
        return this.roles;
    }
    
    public void setRoles(Roles roles) {
        this.roles = roles;
    }
    public String getAutIns() {
        return this.autIns;
    }
    
    public void setAutIns(String autIns) {
        this.autIns = autIns;
    }
    public String getAutUpd() {
        return this.autUpd;
    }
    
    public void setAutUpd(String autUpd) {
        this.autUpd = autUpd;
    }
    public String getAutDel() {
        return this.autDel;
    }
    
    public void setAutDel(String autDel) {
        this.autDel = autDel;
    }




}


