package ModSec.entidades;
// Generated 10-11-2014 10:38:28 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles  implements java.io.Serializable {


     private int id;
     private String codigo;
     private String nombre;
     private String descripcion;
     private Set opcRols = new HashSet(0);

    public Roles() {
    }

	
    public Roles(int id, String codigo, String nombre, String descripcion) {
        this.id = id;
        this.codigo = codigo;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public Roles(int id, String codigo, String nombre, String descripcion, Set opcRols) {
       this.id = id;
       this.codigo = codigo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.opcRols = opcRols;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getOpcRols() {
        return this.opcRols;
    }
    
    public void setOpcRols(Set opcRols) {
        this.opcRols = opcRols;
    }




}


